import type { PromptProduct } from "../lib/promptData";
import { PROMPT_PRODUCTS } from "../lib/promptData";

type Category = PromptProduct["category"];

interface SeedTemplate {
  title: string;
  titleEn: string;
  price: number;
  slug: string;
  tags: string[];
  author: string;
  rating: number;
  views: number;
  salesCount: number;
  promptSnippet: string;
}

const CATEGORY_TEMPLATES: Record<Category, SeedTemplate[]> = {
  Midjourney: [
    {
      title: "Pixar 스타일 3D 입체 캐릭터 생성기",
      titleEn: "Pixar Style 3D Character Generator",
      price: 7900,
      slug: "pixar-char",
      tags: ["Pixar", "3D Character", "Cute"],
      author: "VisualArtisans",
      rating: 4.9,
      views: 1250,
      salesCount: 342,
      promptSnippet: "Pixar animation style 3D character, volumetric lighting, octane render --v 6.0",
    },
    {
      title: "수채화 풍경 일러스트 생성기",
      titleEn: "Watercolor Landscape Illustrator",
      price: 5900,
      slug: "watercolor-landscape",
      tags: ["Watercolor", "Landscape", "Illustration"],
      author: "PaintStudio",
      rating: 4.7,
      views: 980,
      salesCount: 215,
      promptSnippet: "soft watercolor landscape painting, gentle brush strokes, pastel sky --ar 16:9 --v 6.0",
    },
    {
      title: "네온 사이버펑크 도시 스카이라인",
      titleEn: "Neon Cyberpunk City Skyline",
      price: 8900,
      slug: "cyberpunk-city",
      tags: ["Cyberpunk", "Neon", "Cityscape"],
      author: "NeonDreams",
      rating: 4.8,
      views: 1560,
      salesCount: 428,
      promptSnippet: "cyberpunk city skyline at night, neon signs, rain reflections, cinematic --v 6.0",
    },
    {
      title: "미니멀 플랫 아이콘 세트 제너레이터",
      titleEn: "Minimal Flat Icon Set Generator",
      price: 4500,
      slug: "flat-icons",
      tags: ["Flat Design", "Icons", "UI"],
      author: "IconLab",
      rating: 4.6,
      views: 720,
      salesCount: 189,
      promptSnippet: "minimal flat icon set, consistent stroke width, pastel colors, white background --v 6.0",
    },
    {
      title: "레트로 80s 신스웨이브 포스터",
      titleEn: "Retro 80s Synthwave Poster",
      price: 6500,
      slug: "synthwave-poster",
      tags: ["Synthwave", "Retro", "Poster"],
      author: "RetroWave",
      rating: 4.7,
      views: 1100,
      salesCount: 301,
      promptSnippet: "80s synthwave poster, sunset grid, palm trees, chrome text, vaporwave aesthetic --v 6.0",
    },
    {
      title: "건축 인테리어 3D 렌더링",
      titleEn: "Architectural Interior 3D Render",
      price: 9900,
      slug: "interior-render",
      tags: ["Architecture", "Interior", "3D Render"],
      author: "ArchVision",
      rating: 4.8,
      views: 1340,
      salesCount: 367,
      promptSnippet: "modern minimalist interior, natural light, Scandinavian design, photorealistic render --v 6.0",
    },
    {
      title: "판타지 마법사 캐릭터 컨셉 아트",
      titleEn: "Fantasy Wizard Character Concept Art",
      price: 7500,
      slug: "fantasy-wizard",
      tags: ["Fantasy", "Wizard", "Concept Art"],
      author: "MythCraft",
      rating: 4.9,
      views: 1680,
      salesCount: 445,
      promptSnippet: "epic fantasy wizard character, glowing staff, magical aura, detailed robes --v 6.0",
    },
    {
      title: "음식 스타일링 푸드 포토그래피",
      titleEn: "Food Styling Photography Prompt",
      price: 5500,
      slug: "food-photo",
      tags: ["Food", "Photography", "Styling"],
      author: "FoodLens",
      rating: 4.5,
      views: 890,
      salesCount: 178,
      promptSnippet: "professional food photography, overhead shot, natural lighting, rustic wooden table --v 6.0",
    },
  ],
  ChatGPT: [
    {
      title: "구글 상위 노출(SEO) 매직 블로그 메이커",
      titleEn: "Google SEO Magic Blog Maker",
      price: 4900,
      slug: "seo-blog",
      tags: ["SEO", "Copywriting", "Blog"],
      author: "ContentGuru",
      rating: 4.8,
      views: 2430,
      salesCount: 812,
      promptSnippet: "You are an SEO expert. Write a blog post optimized for Google ranking...",
    },
    {
      title: "SNS 인스타그램 캡션 자동 생성기",
      titleEn: "Instagram Caption Auto Generator",
      price: 3900,
      slug: "instagram-caption",
      tags: ["SNS", "Instagram", "Marketing"],
      author: "SocialBoost",
      rating: 4.6,
      views: 1820,
      salesCount: 534,
      promptSnippet: "Generate engaging Instagram captions with hashtags for the given image description...",
    },
    {
      title: "이메일 마케팅 콜드 아웃리치 작성기",
      titleEn: "Cold Email Outreach Writer",
      price: 4500,
      slug: "cold-email",
      tags: ["Email", "Marketing", "Sales"],
      author: "SalesPro",
      rating: 4.7,
      views: 1560,
      salesCount: 423,
      promptSnippet: "Write a personalized cold outreach email that gets responses...",
    },
    {
      title: "유튜브 롱폼 스크립트 작성기",
      titleEn: "YouTube Long-form Script Writer",
      price: 5900,
      slug: "youtube-script",
      tags: ["YouTube", "Script", "Video"],
      author: "VideoCraft",
      rating: 4.8,
      views: 2100,
      salesCount: 678,
      promptSnippet: "Create a YouTube video script with hook, main content, and CTA...",
    },
    {
      title: "제품 상세페이지 카피라이팅",
      titleEn: "Product Detail Page Copywriting",
      price: 5500,
      slug: "product-copy",
      tags: ["E-commerce", "Copywriting", "Sales"],
      author: "CopyMaster",
      rating: 4.7,
      views: 1340,
      salesCount: 389,
      promptSnippet: "Write compelling product page copy with benefits, features, and social proof...",
    },
    {
      title: "회의록 자동 요약 & 액션 아이템",
      titleEn: "Meeting Notes Summary & Action Items",
      price: 3500,
      slug: "meeting-summary",
      tags: ["Productivity", "Meeting", "Summary"],
      author: "WorkFlow",
      rating: 4.5,
      views: 980,
      salesCount: 267,
      promptSnippet: "Summarize the meeting transcript and extract action items with owners...",
    },
    {
      title: "이력서 & 자기소개서 첨삭 가이드",
      titleEn: "Resume & Cover Letter Review Guide",
      price: 4900,
      slug: "resume-review",
      tags: ["Career", "Resume", "Job Search"],
      author: "CareerCoach",
      rating: 4.8,
      views: 1890,
      salesCount: 512,
      promptSnippet: "Review and improve the resume for ATS compatibility and impact...",
    },
    {
      title: "법률 계약서 초안 검토 어시스턴트",
      titleEn: "Legal Contract Draft Review Assistant",
      price: 7900,
      slug: "legal-review",
      tags: ["Legal", "Contract", "Review"],
      author: "LegalAid",
      rating: 4.6,
      views: 760,
      salesCount: 198,
      promptSnippet: "Review the contract draft and identify potential risks and missing clauses...",
    },
  ],
  "Stable Diffusion": [
    {
      title: "시네마틱 아날로그 인물 포트레이트 마스터",
      titleEn: "Cinematic Analog Portrait Master",
      price: 9900,
      slug: "analog-portrait",
      tags: ["SDXL", "Portrait", "Analog Film"],
      author: "FocusMaster",
      rating: 4.7,
      views: 1890,
      salesCount: 450,
      promptSnippet: "RAW photo, cinematic portrait, 35mm film, natural skin texture, Fujifilm...",
    },
    {
      title: "스팀펑크 기계 장치 컨셉 아트",
      titleEn: "Steampunk Machine Concept Art",
      price: 7500,
      slug: "steampunk-machine",
      tags: ["Steampunk", "Concept Art", "Mechanical"],
      author: "GearWorks",
      rating: 4.6,
      views: 1120,
      salesCount: 289,
      promptSnippet: "steampunk mechanical device, brass gears, copper pipes, detailed engraving, SDXL...",
    },
    {
      title: "우주 SF 우주선 내부 장면",
      titleEn: "Sci-Fi Spaceship Interior Scene",
      price: 8500,
      slug: "spaceship-interior",
      tags: ["Sci-Fi", "Spaceship", "Interior"],
      author: "SpaceArt",
      rating: 4.8,
      views: 1450,
      salesCount: 378,
      promptSnippet: "futuristic spaceship cockpit interior, holographic displays, ambient blue lighting, SDXL...",
    },
    {
      title: "수채화 꽃 Bouquet 일러스트",
      titleEn: "Watercolor Flower Bouquet Illustration",
      price: 5500,
      slug: "flower-bouquet",
      tags: ["Watercolor", "Flowers", "Illustration"],
      author: "BloomArt",
      rating: 4.5,
      views: 870,
      salesCount: 201,
      promptSnippet: "delicate watercolor flower bouquet, soft pastel colors, white background, SDXL...",
    },
    {
      title: "로우폴리 3D 캐릭터 모델",
      titleEn: "Low Poly 3D Character Model",
      price: 6500,
      slug: "lowpoly-char",
      tags: ["Low Poly", "3D", "Game Asset"],
      author: "PolyCraft",
      rating: 4.7,
      views: 1230,
      salesCount: 334,
      promptSnippet: "low poly 3D character model, game asset style, flat shading, vibrant colors, SDXL...",
    },
    {
      title: "일본 애니메이션 스타일 배경",
      titleEn: "Japanese Anime Style Background",
      price: 6900,
      slug: "anime-bg",
      tags: ["Anime", "Background", "Makoto Shinkai"],
      author: "AnimeBG",
      rating: 4.9,
      views: 2100,
      salesCount: 567,
      promptSnippet: "anime background art, Makoto Shinkai style, dramatic sky, detailed clouds, SDXL...",
    },
    {
      title: "제품 목업 포토리얼 렌더링",
      titleEn: "Product Mockup Photoreal Render",
      price: 7900,
      slug: "product-mockup",
      tags: ["Product", "Mockup", "Photorealistic"],
      author: "RenderPro",
      rating: 4.6,
      views: 1050,
      salesCount: 278,
      promptSnippet: "photorealistic product mockup on marble surface, studio lighting, commercial photography, SDXL...",
    },
    {
      title: "빈티지 필름 그레인 텍스처 오버레이",
      titleEn: "Vintage Film Grain Texture Overlay",
      price: 4500,
      slug: "film-grain",
      tags: ["Vintage", "Film Grain", "Texture"],
      author: "RetroFilm",
      rating: 4.4,
      views: 680,
      salesCount: 156,
      promptSnippet: "vintage film grain texture overlay, 35mm noise, light leaks, nostalgic aesthetic, SDXL...",
    },
  ],
  Claude: [
    {
      title: "Claude 3.5 Sonnet 풀스택 기획 & 아키텍트 가이드",
      titleEn: "Claude 3.5 Sonnet Full-Stack Planning & Architecture Guide",
      price: 12900,
      slug: "claude-arch",
      tags: ["Claude 3.5", "Architecture", "Fullstack"],
      author: "DevArchitect",
      rating: 5.0,
      views: 3120,
      salesCount: 1105,
      promptSnippet: "You are an elite Staff Software Architect. Output a comprehensive Technical Architecture & PRD...",
    },
    {
      title: "코드 리뷰 & 리팩터링 어드바이저",
      titleEn: "Code Review & Refactoring Advisor",
      price: 8900,
      slug: "code-review",
      tags: ["Code Review", "Refactoring", "Best Practices"],
      author: "CleanCode",
      rating: 4.8,
      views: 1780,
      salesCount: 489,
      promptSnippet: "Review the following code for bugs, performance issues, and suggest refactoring...",
    },
    {
      title: "API 설계 문서 자동 생성기",
      titleEn: "API Design Document Generator",
      price: 9900,
      slug: "api-design",
      tags: ["API", "REST", "Documentation"],
      author: "APIMaster",
      rating: 4.7,
      views: 1340,
      salesCount: 367,
      promptSnippet: "Design a RESTful API specification with endpoints, request/response schemas, and error codes...",
    },
    {
      title: "데이터 파이프라인 아키텍처 가이드",
      titleEn: "Data Pipeline Architecture Guide",
      price: 10900,
      slug: "data-pipeline",
      tags: ["Data Engineering", "Pipeline", "ETL"],
      author: "DataFlow",
      rating: 4.6,
      views: 980,
      salesCount: 234,
      promptSnippet: "Design a scalable data pipeline architecture for the given use case...",
    },
    {
      title: "보안 취약점 분석 체크리스트",
      titleEn: "Security Vulnerability Analysis Checklist",
      price: 11900,
      slug: "security-audit",
      tags: ["Security", "Audit", "OWASP"],
      author: "SecureDev",
      rating: 4.9,
      views: 1560,
      salesCount: 412,
      promptSnippet: "Analyze the codebase for security vulnerabilities following OWASP Top 10...",
    },
    {
      title: "마이크로서비스 마이그레이션 전략",
      titleEn: "Microservices Migration Strategy",
      price: 13900,
      slug: "microservices",
      tags: ["Microservices", "Migration", "Architecture"],
      author: "CloudArch",
      rating: 4.7,
      views: 890,
      salesCount: 198,
      promptSnippet: "Create a phased migration strategy from monolith to microservices...",
    },
    {
      title: "테스트 전략 & TDD 가이드",
      titleEn: "Testing Strategy & TDD Guide",
      price: 7900,
      slug: "tdd-guide",
      tags: ["Testing", "TDD", "Quality"],
      author: "TestCraft",
      rating: 4.8,
      views: 1230,
      salesCount: 345,
      promptSnippet: "Design a comprehensive testing strategy with unit, integration, and E2E tests...",
    },
    {
      title: "클라우드 인프라 비용 최적화 분석",
      titleEn: "Cloud Infrastructure Cost Optimization",
      price: 10900,
      slug: "cloud-cost",
      tags: ["Cloud", "Cost Optimization", "DevOps"],
      author: "CloudOps",
      rating: 4.6,
      views: 760,
      salesCount: 189,
      promptSnippet: "Analyze the cloud infrastructure and suggest cost optimization strategies...",
    },
  ],
};

function buildDescription(title: string, category: Category): string {
  return `${title} — ${category} 카테고리 프리미엄 AI 프롬프트입니다.\n\n전문가가 검증한 고품질 프롬프트로, 즉시 활용 가능한 결과물을 생성합니다.\n\n### [활용 방법]\n1. 프롬프트를 복사하여 해당 AI 도구에 붙여넣으세요.\n2. 필요에 따라 변수(주제, 스타일 등)를 수정하세요.\n3. 생성된 결과물을 프로젝트에 바로 적용하세요.\n\n### [주의사항]\n- ${category} 최신 버전에 최적화되어 있습니다.\n- 상업적 이용 시 각 AI 서비스 이용약관을 확인하세요.`;
}

function buildDescriptionEn(titleEn: string, category: Category): string {
  return `${titleEn} — A premium AI prompt in the ${category} category.\n\nExpert-verified high-quality prompt for immediate, production-ready results.\n\n### [How to Use]\n1. Copy the prompt and paste it into your AI tool.\n2. Adjust variables (topic, style, etc.) as needed.\n3. Apply the generated output directly to your project.\n\n### [Notes]\n- Optimized for the latest ${category} version.\n- Review each AI service's terms of use for commercial applications.`;
}

export function buildSeedProducts(): Omit<PromptProduct, "id">[] {
  const products: Omit<PromptProduct, "id">[] = [];

  for (const [category, templates] of Object.entries(CATEGORY_TEMPLATES) as [Category, SeedTemplate[]][]) {
    for (const tmpl of templates) {
      const staticMatch = PROMPT_PRODUCTS.find((p) => p.title === tmpl.title);
      products.push({
        title: tmpl.title,
        titleEn: tmpl.titleEn,
        price: tmpl.price,
        category,
        description: staticMatch?.description ?? buildDescription(tmpl.title, category),
        descriptionEn: staticMatch?.descriptionEn ?? buildDescriptionEn(tmpl.titleEn, category),
        images: staticMatch?.images ?? [
          `https://picsum.photos/seed/${tmpl.slug}-1/800/600`,
          `https://picsum.photos/seed/${tmpl.slug}-2/800/600`,
        ],
        prompt_text: staticMatch?.prompt_text ?? tmpl.promptSnippet,
        tags: tmpl.tags,
        rating: tmpl.rating,
        author: tmpl.author,
        views: tmpl.views,
        salesCount: tmpl.salesCount,
      });
    }
  }

  return products;
}

export const SEED_PRODUCT_COUNT = 32;
